// sidebars.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Autogenerate the sidebar from the docs/general folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'general' }],
  
  // Automatically generate a sidebar from the docs/developers folder structure for the "Developers" section
  developersSidebar: [{ type: 'autogenerated', dirName: 'developers' }],
};

export default sidebars;
