// sidebars.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Autogenerate the sidebar from the docs/general folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'general' }],
  
  // Manually create a sidebar for the "Developers" section without a top-level category
  developersSidebar: [
    'developers/getstarted',
    'developers/networkEndpoints',
    'developers/faq',
    'developers/indexing',
    'developers/oracles',
    {
      type: 'category',
      label: 'Tutorials',
      "collapsed": false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'developers/tutorials/Build dApp',
        },
        {
          type: 'autogenerated',
          dirName: 'developers/tutorials/Deploy',
        },
      ],
    },
  ],
};

export default sidebars;
